//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace RainMaker.UserControls {
    
    
    public partial class cntBrowsingDeadIssue {
        
        /// <summary>
        /// pnlTS21_1NodePortStatus control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlTS21_1NodePortStatus;
        
        /// <summary>
        /// pnlTS21_2TrafficStatusatNodePort control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlTS21_2TrafficStatusatNodePort;
        
        /// <summary>
        /// pnlTS21_3TrafficUtilizationatNodePort control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlTS21_3TrafficUtilizationatNodePort;
        
        /// <summary>
        /// pnlTS21_4TrafficUtilizationatSTG control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlTS21_4TrafficUtilizationatSTG;
        
        /// <summary>
        /// pnlTS21_5TrafficUtilizationatCTG control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlTS21_5TrafficUtilizationatCTG;
        
        /// <summary>
        /// pnlTS21_6ErrorDiscards control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlTS21_6ErrorDiscards;
        
        /// <summary>
        /// pnlTS21_7LastMileDevicePowerStatus control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlTS21_7LastMileDevicePowerStatus;
        
        /// <summary>
        /// pnlTS21_8CPEStatus control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlTS21_8CPEStatus;
        
        /// <summary>
        /// pnlTS22_1FiberLEDStatus control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlTS22_1FiberLEDStatus;
        
        /// <summary>
        /// pnlTS22_2TrafficStatusatCEInterface control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlTS22_2TrafficStatusatCEInterface;
        
        /// <summary>
        /// pnlTS22_3CEInterfaceStatus control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlTS22_3CEInterfaceStatus;
        
        /// <summary>
        /// pnlTS22_4BandwidthUtilization control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlTS22_4BandwidthUtilization;
        
        /// <summary>
        /// pnlTS22_5DeviceRebooted control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlTS22_5DeviceRebooted;
        
        /// <summary>
        /// pnlTS22_6CustomerIPResponse control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlTS22_6CustomerIPResponse;
        
        /// <summary>
        /// pnlTS22_7CustomerBandwidthIssue control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlTS22_7CustomerBandwidthIssue;
        
        /// <summary>
        /// cmbTS22_7CustomerBandwidthIssue control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList cmbTS22_7CustomerBandwidthIssue;
        
        /// <summary>
        /// pnlTS23_1GatewayResponses control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlTS23_1GatewayResponses;
        
        /// <summary>
        /// pnlTS23_2AssignedDNS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlTS23_2AssignedDNS;
        
        /// <summary>
        /// pnlTS23_3DNSResponding control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlTS23_3DNSResponding;
        
        /// <summary>
        /// pnlTS23_4IPBlockedbyPTA control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlTS23_4IPBlockedbyPTA;
        
        /// <summary>
        /// tbTS23_5Remarks control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox tbTS23_5Remarks;
    }
}
